### ISSUE TITLE
ES5 / ES6 dynamic require in index.js doesn't work with browserify

### ISSUE THREAD

**Issue by lakemalcom** [thiagobustamante/typescript-ioc#14]
I end up with: Uncaught Error: Cannot find module './es5'

If I change the output from:
module.exports = require(useES6 ? './es6' :  './es5');
to:
module.exports = require('./es5');

Then everything works fine.

**Comment by romantymchenko** [comment]
I have the same issue, please tell where exactly you've changed that? I'm new in typescript

**Comment by dpanelli** [comment]
Is there a release planned with this?

**Comment by thiagobustamante** [comment]
Please, refer to [this](https://github.com/thiagobustamante/typescript-ioc#browser-usage) section in the documentation.

When using with browserify, webpack etc, you must import the library as:

```typescript
import {AutoWired, Inject} from "typescript-ioc/es5";
```

or, if you are using es6 as output:

```typescript
import {AutoWired, Inject} from "typescript-ioc/es6";
```
