### ISSUE TITLE
Use of const breaks minifiers

### ISSUE THREAD

**Issue by nickhod** [thiagobustamante/typescript-ioc#15]
I really like typescript-ioc but currently the code uses "const". The Typescript compiler doesn't compile this to var. This means that for browser based projects, only >= IE 11 is supported.
I've also found that most Javascript minifiers break on the keyword const. (The popular VisualStudio Minifier & Bundler being one).

Currently I'm having to use my modified version of the library that removes instances of "const".

**Comment by pklochkov** [comment]
@nickhod  I think you can use es5.js to solve your problem. Also if you compile code with typescript you can specify "target":"es2015" or lower in tsconfig.json

![image](https://user-images.githubusercontent.com/13065714/32010297-1b99b8da-b9ba-11e7-9b4f-c4c86dd511ae.png)
