### ISSUE TITLE
Possibility to have a factory or bind an already created instance to a type?

### ISSUE THREAD

**Issue by nolazybits** [thiagobustamante/typescript-ioc#16]
Just wondering if this is possible.
Couldn't find an example anywhere..
Thanks

**Comment by westinpigott** [comment]
Doesn't having an already instantiated object bound to a type defeat the purpose?  Just not sure on the use case.

If you want to do it, you can try something like this:  (Not tested)
```typescript
Container.bind(SomeType).provider({
       get: () => { return existingObject; }
});
```

**Comment by nolazybits** [comment]
Use case is when object creation is outside of my reach yet I want to be able to use it part of the DI.
Regards
