### ISSUE TITLE
get the type registered as provided

### ISSUE THREAD

**Issue by nolazybits** [thiagobustamante/typescript-ioc#25]
Is it possible to expose the type provided like for instance
`Container.bind(PersonDAO).to(ManagerDAO);`
having a 
`Container.getType(PersonDAO)` would return the ManagerDAO type.

The use case is for instance, i am using [class-transformer](https://github.com/typestack/class-transformer) which requires the type needed when you want to create a object from plain json.

**Comment by nolazybits** [comment]
I have added a PR here
https://github.com/thiagobustamante/typescript-ioc/pull/26

Thanks :)

**Comment by thiagobustamante** [comment]
Thanks!
