### ISSUE TITLE
Search for config file does not work on windows

### ISSUE THREAD

**Issue by Morcatko** [thiagobustamante/typescript-ioc#27]
Hello,
I just installed v1.2.0 and my app does not start.
After some debugging I found a culprit in this commit - https://github.com/thiagobustamante/typescript-ioc/commit/3f0a3521c14d424bc594e93f8a652c61a2fe2d1f

It stucks in infite loop because `configFile === ROOT` never happens.

the ROOT is `\ioc.config`, but the configFile on windows ends up as `C:\ioc.config`

PS: Great work with typescript-ioc BTW. From all IOC libraries I found your one is the easiest to use.

**Comment by thiagobustamante** [comment]
Thanks for reporting!

Already published a new version to fix it. Please, try again with 1.2.1 version

**Comment by Morcatko** [comment]
That was super-fast. Works great. Thanks
