### ISSUE TITLE
Could not find a declaration file for module 'typescript-ioc/es5'

### ISSUE THREAD

**Issue by rainmanhhh** [thiagobustamante/typescript-ioc#42]
import {Inject, AutoWired} from 'typescript-ioc/es5'

webstorm report error:
TS7016: Could not find a declaration file for module 'typescript-ioc/es5'

**Comment by soleshot** [comment]
I had the same issue; ended up leaving the import statement alone to make typescript happy

`import {Inject, AutoWired} from 'typescript-ioc'`

and then adding an alias to your resolver (i.e. webpack config resolve alias for me)
`resolve: {
        alias: {
            "typescript-ioc": path.resolve("node_modules/typescript-ioc/es5.js")
        }
    }`

**Comment by Bielik20** [comment]
As we had this (and other) issues with that library at Wikia, so we created our own, it is heavily inspired by this one but assumes different paradigm, and is built with web in mind: https://github.com/Wikia/dependency-injection-js

**Comment by thiagobustamante** [comment]
After version 2, this library does not support es5 anymore, so we don't have this kind of imports
