### ISSUE TITLE
Set constants

### ISSUE THREAD

**Issue by pvieira91** [thiagobustamante/typescript-ioc#45]
Is there a way to set constants to container?

For example
const config:IConfig = {
  connectionString: "xpto"
};

Container.bind(config).provider(config).

**Comment by Bielik20** [comment]
We have just added symbol injection support to our library at wikia: https://github.com/Wikia/dependency-injection-js

It assumes different approach from this library, but was inspired by it.

You can do something like:

```ts
@Injectable()
class TestClass {
  constructor(@Inject('symbol') public config: IConfig) {}
}

const container = new Container();
const config: IConfig = {
  connectionString: "xpto"
}

container.bind('symbol').to(config);

const instance = container.get(TestClass);
```

**Comment by thiagobustamante** [comment]
Hi @pvieira91 . It is finally available.

I documented how to use it [here](https://github.com/thiagobustamante/typescript-ioc#injectvalue-decorator-and-constants).
