### ISSUE TITLE
@InjectValue annotation is not correctly exported

### ISSUE THREAD

**Issue by aelayeb** [thiagobustamante/typescript-ioc#65]
I wanted to use the @InjectValue annotation like in the documentation, but is was not exported at the module level like with @Inject and other annotations.
So currently I must import it from 'typescript-ioc/dist/decorators' but I don't think it's the intended way.

**Comment by fingercoder** [comment]
I also meet it

**Comment by thiagobustamante** [comment]
Fixed in release 3.2.2
